#!/bin/sh

[ -f ~/.pubkey ] ||
	ssh-add -L | grep -s -- ' angt$' > ~/.pubkey

gen() {
	echo "$1" | ssh-keygen -Y sign -f ~/.pubkey -n clipboard-key 2>/dev/null | sha256sum | cut -d' ' -f1
}

pass=$(gen you-shall-not-pass) || exit
tobe=$(gen to-be-or-not-to-be) || exit

case "$0" in
(*s) zstd --fast | encpipe -e -p "$pass" | curl -sS -T - "https://ppng.io/$tobe" ;;
(*g) curl -sS -N "https://ppng.io/$tobe" | encpipe -d -p "$pass" | zstd -d -q ;;
esac
