#!/bin/sh

CMD="$(which -a install | sed -n 2p)"
MKD=
DST=

for arg; do
	case "$arg" in
		-D)   MKD=1; continue;;
		-*D*) MKD=1; arg="${arg%%D*}${arg##-*D}";;
		-*)   ;;
		*/*)  DST="$arg";;
	esac
	CMD="$CMD \"$arg\""
done

[ "$MKD" ] && [ "$DST" ] && (umask 022; mkdir -p "${DST%/*}")

exec $CMD
