#!/bin/sh

[ -r "$1" ] || exit

D=$(printf "%s" "$1" \
	| iconv -c -t ASCII//TRANSLIT//IGNORE \
	| tr -c '[[:alnum:]]._' '-' \
	| tr '[:upper:]' '[:lower:]')

[ "$D" ] || exit

echo " -> $D"
cp -- "$1" "$D"
