#! /bin/sh

xautolock -time 5 -locker slock -lockaftersleep &
xsetroot -cursor_name left_ptr &

sxhkd &

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a chromium desktop=^2
bspc rule -a mpv state=floating

urxvt &
chromium &
